# Generated by Django 2.2.4 on 2019-08-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_wars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CastingManagers',
            new_name='CastingManager',
        ),
        migrations.RenameModel(
            old_name='Contestans',
            new_name='Contestan',
        ),
    ]
