# Generated by Django 2.2.4 on 2019-08-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_wars', '0003_auto_20190804_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestan',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_wars.Character'),
        ),
    ]
