# Generated by Django 2.2.4 on 2019-08-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_wars', '0004_auto_20190807_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestan',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_wars.Character'),
        ),
    ]
